### PR TITLE
Create divide-array-into-equal-pairs

### PR DESCRIPTION
**Pull request by baibhav-tiwari**
ceated a file which contains the C++ code of how to divide any array into two equal parts..

### CODE REVIEW

**Review by baibhav-tiwari — COMMENTED** [review]
added the platform name ans well as the problem link.

**Review by ayu8 — CHANGES_REQUESTED** [review]
I appreciate this but I'd request you to read `CONTRIBUTING.md` once

I have mentioned that:

- Only add solutions to the questions which are on any coding platform, with the link to that question.
- No need to add driver-code for the problem or the main() function.
- File should contain the solution code as well as the link to that question (as comment in the code).
- The name of the file should follow snake_case convention.
- Create file under appropriate folder (topic).

Please follow all :)


You should change the name of the file as divide_array_into_equal_pairs.cpp

**Review by baibhav-tiwari — COMMENTED** [review]
changed the file name to divide-array-into-equal-pairs.cpp

**Comment by baibhav-tiwari** [comment]
> I appreciate this but I'd request you to read `CONTRIBUTING.md` once
> 
> I have mentioned that:

**Pull request merged**
