### PR TITLE
Added code for implementation of Stacks

### PR DESCRIPTION
**Pull request by Anmol-Prasad**
Hi Ayush! I have added code for implementation of Stacks in C++ from scratch. Hope you'd like it

### CODE REVIEW

**Comment by ayu8** [comment]
Hey @Anmol-Prasad 
I appreciate this but I'd request you to read CONTRIBUTING.md once

I have mentioned that:

- Only add solutions to the questions which are on any coding platform, with the link to that question.
- No need to add driver-code for the problem or the main() function.
- File should contain the solution code as well as the link to that question (as comment in the code).
- The name of the file should follow snake_case convention.
- Create file under appropriate folder (topic).

**Comment by Anmol-Prasad** [comment]
Ok sure I'll add my solutions for some good problems I practised on CodeChef

**Comment by ayu8** [comment]
Okay, please add the link to that question (as a comment) and only include solution (not entire driver code and main() function)

**Comment by Anmol-Prasad** [comment]
Yes sure, I have uploaded the code once again in exactly the way you asked
for in CONTRIBUTING.md. You may check it once
Thanks

**Pull request closed without merging**
